### ISSUE TITLE
アイコンとソーシャルPreviewを作ってもらう

### ISSUE THREAD

**Issue by 75asa** [75asa/fondeSlack#14]
# ほしいもの
- [x] SlackApp 用アイコン
  - 512px x 512px か 2000px x 2000px
- [x] GitHub Social Preview 用サムネ
  - 640×320px (1280×640px for best display)

# どんなアイコンがいいか
- 本家の fondesk 反転させて色が緑か紫系統のやつがいいかも 🙄 （Evaリスペクト）

# メモ
＠tamaito にお願い

**Comment by tamaito** [comment]
[fondesk_icon.zip](https://github.com/75asa/fondeSlack/files/5621761/fondesk_icon.zip)
@75asa 
画像の渡し方これで合ってるのか分かんないんですけど、とりあえずここに紫と緑のパターンをupしておきます！
間違ってたり直してほしいところあったら言ってください！

**Comment by 75asa** [comment]
@tamaito ありがとう！
あとこっちももらえますと//

>  GitHub Social Preview 用サムネ

**Comment by 75asa** [comment]
@tamaito ありがとう！SlackApp は一旦ピンクで行きます 👁️ 
![image](https://user-images.githubusercontent.com/35181442/100755998-1d533900-3430-11eb-96d9-2e322e0ff3ab.png)

**Comment by tamaito** [comment]
[fondesk_preview_thumbnail.zip](https://github.com/75asa/fondeSlack/files/5627160/fondesk_preview_thumbnail.zip)
@75asa 
サムネイル版作りました！

**Comment by 75asa** [comment]
@tamaito ありがとう！！！確認できました！！！
